id: IF8E22228
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T17:46:08+00:00'
last_modified: '2022-06-07T12:34:22.060065+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD925
  title: མཁའ་འགྲོ་གསང་བ་ཀུན་འདུས་ཀྱི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9899':
      image_group_id: I4PD2034
      title: ''
      total_pages: 452
      order: 1
      base_file: 9899.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
