id: P000657
initial_creation_type: ocr
source_metadata:
  id: bdr:W4PD925
  title: མཁའ་འགྲོ་གསང་བ་ཀུན་འདུས་ཀྱི་ཆོས་སྐོར།
  author: ''
  volumes:
    4f04aaa5e9ad489aaf82e370dddd0c87:
      image_group_id: I4PD2034
      title: ''
      volume_number: 1
      total_pages: 452
