id: P000657
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:57:38.165220
source_metadata:
  id: bdr:W4PD925
  title: མཁའ་འགྲོ་གསང་བ་ཀུན་འདུས་ཀྱི་ཆོས་སྐོར།
  author: ''
  volumes:
    4f04aaa5e9ad489aaf82e370dddd0c87:
      image_group_id: I4PD2034
      title: ''
      volume_number: 1
      total_pages: 452
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
